### PR TITLE
joyent/triton-prometheus#1 relabel terminology consistency

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by trentm** [comment]
This would require updates to all the dashboards right? E.g. things like `... "expr": "cpucap_effective_percentage{instance=~\"manatee0\"}", ...`

I'm not opposed at all. The consistency would be nice with, e.g. SAPI's and sdcadm's usage of "instance" to be the instance UUID.

**Comment by trentm** [comment]
If/when we make this change we should also update:

1. https://github.com/joyent/triton-prometheus/blob/prod-lx-scripts/setup-prometheus-prod.sh and
2. https://github.com/joyent/triton-prometheus/blob/grr-MANTA-3552/boot/setup.sh

that @isaacdavis  and I are working on currently.

**Comment by cburroughs** [comment]
> This would require updates to all the dashboards right

Yep, I think I got the `sed` straight in https://github.com/joyent/triton-dashboards/pull/1

**Comment by cburroughs** [comment]
What's the path forward for merging?

**Pull request merged**
